# Generated by Django 4.2.30 on 2026-05-07 12:14

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('agile', '0002_alter_users_id'),
    ]

    operations = [
        migrations.AddField(
            model_name='users',
            name='username',
            field=models.CharField(max_length=10, null=True, unique=True),
        ),
    ]
