# Generated by Django 4.2.30 on 2026-05-08 16:42

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('agile', '0003_users_username'),
    ]

    operations = [
        migrations.AlterField(
            model_name='userfavourites',
            name='lat',
            field=models.FloatField(),
        ),
        migrations.AlterField(
            model_name='userfavourites',
            name='lon',
            field=models.FloatField(),
        ),
    ]
